version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  netdata:
    restart: always
    image: netdata/netdata:latest
    hostname: "localhost" # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    networks:
      - app-network
    security_opt:
      - apparmor:unconfined
    volumes:
      # - /etc/passwd:/host/etc/passwd:ro
      # - /etc/group:/host/etc/group:ro
      # - /etc/os-release:/host/etc/os-release:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - "../configs/${NODE_ENV}/netdata/netdata.conf:/etc/netdata/netdata.conf"
    environment:
      - DOCKER_USR=root
      # - "PGID=998" # Comentar en prod/dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-network
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge 